name: Deploy to GitHub Pages

on:
  push:
    branches:
      - backup-full-system

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # Use PAT token instead of default GITHUB_TOKEN for deployment authentication
        github_token: ${{ secrets.PAT_TOKEN }}
        publish_dir: ./public
        publish_branch: live-test
